### ISSUE TITLE
Bottom sheet can be lifted above the bottom of the screen

### ISSUE THREAD

**Issue by serzhikivanov** [grendio/XBottomSheet#5]
Hello!
I've added the Bottom Sheet to my project and there is an issue I'm not sure how to handle - bottom sheet can be... "picked above" the bottom of the screen.
Initial state:
![Screenshot 2019-12-24 at 18 23 33](https://user-images.githubusercontent.com/33659039/71418798-886f8980-267d-11ea-9538-0f63dd681c90.png)
and it can be drug above until screen allows like this
![Screenshot 2019-12-24 at 18 23 13](https://user-images.githubusercontent.com/33659039/71418819-9c1af000-267d-11ea-93d8-416661f75ea4.png)
Is there a way to "glue" it to the bottom of the screen so it's impossible to detach it from the screen bottom?

Thanks

**Comment by AlexStefan** [comment]
Sorry for really late response. I've just uploaded a beta version on nuget: https://www.nuget.org/packages/XBottomSheet/1.0.4-beta. This version contains fix for the issue created by you.
